#!/usr/bin/env python3
"""Render evidence/discovery/dependency_table.md (all pins, patch hashes, apply-check) from subject.lock.json and
evidence/discovery/dependency_patch_check.tsv. Stdlib only."""
import csv, json, os, sys
R = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
lock = json.load(open(f"{R}/subject.lock.json")); env = lock["environment_layer"]
chk = {r["package"]: r for r in csv.DictReader(open(f"{R}/evidence/discovery/dependency_patch_check.tsv"), delimiter="\t")}
rows = ["| # | package | kind | git URL (fetched by Lake) | pinned rev | patch sha256 | patch applies to pinned rev (git apply --check) |", "|---|---|---|---|---|---|---|"]
for i, (n, d) in enumerate(sorted(env["dependency_pins"].items(), key=lambda kv: (kv[1]["inherited"], kv[0].lower())), 1):
    c = chk.get(n)
    rows.append(f"| {i} | {n} | {'inherited ('+d['inputRev']+')' if d['inherited'] else 'direct'} | {d['url']} | `{d['rev']}` | {('`'+c['patch_sha256']+'`') if c else '-'} | {(c['apply_check']+' ('+c['files_touched']+' files)') if c else '-'} |")
open(f"{R}/evidence/discovery/dependency_table.md", "w").write("# Dependency pins, patches (generated by scripts/render_dependency_table.py)\n\nSource: lean/lake-manifest.json @ adc7f12 and lean/patches/. Patch check: scripts/check_dependency_patches.sh (network).\n\n" + "\n".join(rows) + "\n")
print(len(rows) - 2, "rows")
